version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=avito_db
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    # depends_on:
      # - postgres
    # env_file:
    #   - .env
  # app:
  #   build: ./
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"